version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
  updater:
    build: .
    image: rintaromasuda/bleaguer-updater
    links:
      - selenium:selenium
    depends_on:
      - selenium
    volumes:
      - ./delta:/delta
      - ./output:/output
    environment:
      - SEASON=2020-21
      - WEBDRHOSTNAME=selenium
